<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(Mi URL trn mt dng)_url</name>
   <tag></tag>
   <elementGuidId>8447a240-0b5d-495b-a483-0e3737c08e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='url']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0f71937a-0138-418a-b30d-374746f8305e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>47483932-7d0c-4b3d-995b-fc4b239bdcf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>eb55aa3b-5993-4f42-aff5-16018ab8c560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expandable-input z-40</value>
      <webElementGuid>96622290-e803-4153-b5ad-3616f27d6cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập đường dẫn</value>
      <webElementGuid>e5dfa864-5148-4a45-8579-ac4b38291c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;url&quot;)</value>
      <webElementGuid>62302ba6-e1e2-4e83-a998-b8ded5aedfe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='url']</value>
      <webElementGuid>d421e13b-cb36-455e-82ac-764b8de97266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-url-extract']/div/textarea</value>
      <webElementGuid>cbc8d6b9-a757-4864-9372-1136e0dca4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>07656345-aee1-4f4d-90d0-8c34ebab5beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'url' and @name = 'url' and @placeholder = 'Nhập đường dẫn']</value>
      <webElementGuid>9f297fe4-548d-46c2-9486-de2dacd4a0ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
